Repository daniel8rc/hackathon_optimizacion_entregas_material, pull requests merged in 2020-04, with the labels that each got.

#3 Adding git clone to Readme.md
  README.md
Labels: documentation

#5 Adding automatization
  README.md
  install.bat
  scripts/dependencies.bat
  scripts/pydependencies.bat
Labels: good first issue

#21 Integration to master
  .env.example
  README.md
  app/__init__.py
  app/config.py
  app/models.py
  app/modules/dealer.py
  app/modules/donor.py
  app/modules/manager.py
  app/schemas.py
  app/templates/auth/index.html
  app/templates/layouts/auth.html
  install.bat
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/f55d3b92560b_.py
  mockups/BBDDv1.png
  my-postgres.conf
  requirements.txt
  resources/scss/components/_index.scss
  scripts/dependencies.bat
  scripts/development.bat
  scripts/iespresso's app/LICENSE.txt
  scripts/iespresso's app/README.md
  scripts/iespresso's app/Title.bat
  scripts/iespresso's app/clean.bat
  scripts/iespresso's app/del-ia.sed
  scripts/iespresso's app/espresso.png
  scripts/iespresso's app/espresso.svg
  scripts/iespresso's app/iespress.bat
  scripts/iespresso's app/iespress.vbs
  scripts/iespresso's app/post.bat
  scripts/pydependencies.bat
  webpack.mix.js
Labels: dependencies

#22 Fixing some venv issues
  .gitignore
  scripts/iespresso's app/iespress.bat
  venv/.gitignore
  venv/checkIfExist.bat
  venv/pyvenv.cfg
  venv/pyvenv36.cfg
Labels: dependencies

#23 fixing venv generation issue
  README.md
  install.bat
  scripts/dependencies.bat
  scripts/pydependencies.bat
Labels: bug
